name: C++ Video Sketch Effect Build

on:
  push:
    paths:
      - 'inputs/**'
      - '*.cpp'
      - '*.h'
      - 'CMakeLists_build.txt'

permissions:
  contents: write

jobs:
  build-process:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup C++ environment
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
          cmake: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopencv-dev ffmpeg pkg-config

      - name: Copy CMake file
        run: |
          cp CMakeLists_build.txt CMakeLists.txt

      - name: Build application
        run: |
          mkdir build_build
          cd build_build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Test build
        run: |
          cd build_build
          ./sketch_video_build --version || echo "Build completed successfully"

      - name: Process videos
        run: |
          mkdir -p outputs_build
          for f in inputs/*.{mp4,mkv,avi,mov}; do
            [ -f "$f" ] || continue
            base=$(basename "$f" | cut -d. -f1)
            echo "Processing: $f"
            ./build_build/sketch_video_build "$f" "outputs_build/sketched_build_$base.mp4" $(nproc)
          done

      - name: List processed outputs
        run: |
          echo "=== Build Results ==="
          ls -la outputs_build/ || echo "No outputs generated"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: processed-videos-build-${{ github.run_number }}
          path: outputs_build/
          if-no-files-found: warn

      - name: Commit processed videos
        run: |
          git config user.name "Video Build Processor"
          git config user.email "build-processor@github.actions"
          git add outputs_build/
          git commit -m "Add processed sketch videos from build [$(date)]" || exit 0
          git push
          
