name: C++ Video Sketch Effect

on:
  push:
    paths:
      - 'inputs/**'

permissions:
  contents: write

jobs:
  process-video:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup C++ environment
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
          cmake: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopencv-dev ffmpeg pkg-config
        shell: bash

      - name: Build application
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
        shell: bash

      - name: List inputs
        run: ls -la inputs/ || echo "No inputs folder"
        shell: bash

      - name: Process videos
        run: |
          mkdir -p outputs
          for f in inputs/*.mp4 inputs/*.mkv inputs/*.avi inputs/*.mov; do
            if [ -f "$f" ]; then
              filename=$(basename "$f")
              base="${filename%.*}"
              output="outputs/sketched_${base}.mp4"
              echo "Processing: $filename"
              ./build/sketch_video "$f" "$output" $(nproc) false
            fi
          done
        shell: bash

      - name: List outputs
        run: ls -la outputs/ || echo "No outputs generated"
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processed-videos-${{ github.run_number }}
          path: outputs/
          if-no-files-found: warn

      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add outputs/ || true
          git commit -m "Add processed videos" || echo "No changes"
          git push || echo "Push failed"
        shell: bash
