name: C++ Video Sketch Effect

on:
  push:
    paths:
      - 'inputs/**'

permissions:
  contents: write

jobs:
  process-video:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup C++
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
          cmake: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopencv-dev ffmpeg pkg-config

      - name: Build application
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Process videos
        run: |
          mkdir -p outputs
          for f in inputs/*.{mp4,mkv,avi,mov}; do
            [ -f "$f" ] || continue
            base=$(basename "$f" | cut -d. -f1)
            echo "Processing: $f"
            ./build/sketch_video "$f" "outputs/sketched_$base.mp4" $(nproc) false
          done

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: videos-${{ github.run_number }}
          path: outputs/

      - name: Commit back
        run: |
          git config user.name "Actions"
          git config user.email "actions@github.com"
          git add outputs/
          git commit -m "Add processed videos" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
