name: Video Sketch Effect Workflow

on:
  push:
    paths:
      - 'inputs/**'  # Triggers when files are pushed to the inputs/ folder

jobs:
  process-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sketch effect script
        run: |
          # Assuming input is in inputs/ and output goes to outputs/
          python sketch_video.py --input inputs/example_video.mp4 --output outputs/sketched_video.mp4

      - name: Commit and push output
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add outputs/
          git commit -m "Add processed sketch video output" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This allows pushing back to the repo
