name: Video Sketch Effect Workflow

on:
  push:
    paths:
      - 'inputs/**'  # Trigger only when files are pushed to inputs/

jobs:
  process-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg  # Needed for OpenCV video writing

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug inputs
        run: |
          echo "Listing inputs:"
          ls -la inputs/ || echo "Inputs folder missing or empty"

      - name: Run sketch effect script for all .mp4 files
        run: |
          mkdir -p outputs
          shopt -s nullglob
          for f in inputs/*.mp4; do
            filename=$(basename "$f")
            output="outputs/sketched_$filename"
            echo "Processing $filename -> $output"
            python sketch_video.py --input "$f" --output "$output"
          done

      - name: Debug outputs
        run: |
          echo "Listing outputs:"
          ls -la outputs/ || echo "Outputs folder missing or empty"

      - name: Commit and push outputs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add outputs/ || true
          git commit -m "Add processed sketch video outputs" || echo "No changes to commit"
          git push || echo "Push failed - check logs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            echo "Input file not found: inputs/example_video.mp4"
          fi

      - name: Run sketch effect script
        run: |
          python sketch_video.py --input inputs/example_video.mp4 --output outputs/sketched_video.mp4 2>&1 || echo "Script failed - check above for errors"

      - name: Debug output files
        run: ls -la outputs/ || echo "Outputs folder is empty"

      - name: Commit and push output
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add outputs/ || true  # Ignore if no files to add
          git commit -m "Add processed sketch video output" || echo "No changes to commit"
          git push || echo "Push failed - check logs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This allows pushing back to the repo
