name: Video Sketch Effect Workflow

on:
  push:
    paths:
      - 'inputs/**'

permissions:
  contents: write

jobs:
  process-video:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
        shell: bash

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found — continuing"
          fi
        shell: bash

      - name: List inputs
        run: |
          echo "Listing inputs directory:"
          ls -la inputs/ || true
        shell: bash

      - name: Process videos (mp4/mkv/avi/mov)
        run: |
          set -euo pipefail
          mkdir -p outputs
          shopt -s nullglob
          files=(inputs/*)
          video_files=()
          for f in "${files[@]}"; do
            case "${f,,}" in
              *.mp4|*.mkv|*.avi|*.mov) video_files+=("$f") ;;
            esac
          done
          if [ ${#video_files[@]} -eq 0 ]; then
            echo "No supported video files found in inputs/ — nothing to do"
            exit 0
          fi
          for f in "${video_files[@]}"; do
            filename=$(basename "$f")
            base="${filename%.*}"
            output="outputs/sketched_${base}.mp4"
            echo "Processing: $filename -> $output"
            python sketch_video.py --input "$f" --output "$output"
          done
        shell: bash

      - name: List outputs
        run: |
          echo "Listing outputs directory:"
          ls -la outputs/ || true
        shell: bash

      - name: Upload processed videos (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: processed-videos-${{ github.run_id }}
          path: outputs/
          if-no-files-found: error          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found — continuing without pip installs"
          fi
        shell: bash

      - name: Debug inputs
        run: |
          echo "Listing inputs directory:"
          ls -la inputs/ || echo "Inputs folder missing or empty"
        shell: bash

      - name: Process all video files (mp4/mkv/avi/mov)
        run: |
          set -euo pipefail
          mkdir -p outputs
          shopt -s nullglob
          files=(inputs/*.{mp4,mkv,avi,mov})
          if [ ${#files[@]} -eq 0 ]; then
            echo "No video files found in inputs/ — nothing to do"
            exit 0
          fi
          for f in "${files[@]}"; do
            filename=$(basename "$f")
            base="${filename%.*}"
            output="outputs/sketched_${base}.mp4"
            echo "Processing: $filename -> $output"
            python sketch_video.py --input "$f" --output "$output"
          done
        shell: bash

      - name: Debug outputs
        run: |
          echo "Listing outputs directory:"
          ls -la outputs/ || echo "Outputs folder missing or empty"
        shell: bash

      - name: Check for new outputs
        id: check_outputs
        run: |
          shopt -s nullglob
          files=(outputs/*.mp4)
          if [ ${#files[@]} -eq 0 ]; then
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "found=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Upload processed videos as artifact
        if: steps.check_outputs.outputs.found == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: sketch-outputs-${{ github.run_number }}-${{ github.run_attempt }}-${{ github.sha }}
          path: outputs/
          if-no-files-found: error

      - name: Commit and push outputs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add outputs/ || true
          git commit -m "Add processed sketch video outputs" || echo "No changes to commit"
          git push || echo "Push failed - check logs"
        shell: bash
