name: Video Sketch Effect Workflow

on:
  push:
    paths:
      - 'inputs/**'

permissions:
  contents: write

jobs:
  process-video:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
        shell: bash

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Debug inputs
        run: |
          echo "Listing inputs:"
          ls -la inputs/ || echo "Inputs folder missing or empty"
        shell: bash

      - name: Run sketch effect script for all video files
        run: |
          mkdir -p outputs
          shopt -s nullglob
          # process mp4/mkv/avi/mov — change or extend as needed
          for f in inputs/*.{mp4,mkv,avi,mov}; do
            [ -e "$f" ] || continue
            filename=$(basename "$f")
            # keep original extension handled by your script; here we normalize output name
            output="outputs/sketched_${filename%.*}.mp4"
            echo "Processing $filename -> $output"
            python sketch_video.py --input "$f" --output "$output"
          done
        shell: bash

      - name: Debug outputs
        run: |
          echo "Listing outputs:"
          ls -la outputs/ || echo "Outputs folder missing or empty"
        shell: bash

      - name: Commit and push outputs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add outputs/ || true
          git commit -m "Add processed sketch video outputs" || echo "No changes to commit"
          git push || echo "Push failed - check logs"
        shell: bash      - name: Debug output files
        run: ls -la outputs/ || echo "Outputs folder is empty"

      - name: Commit and push output
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add outputs/ || true  # Ignore if no files to add
          git commit -m "Add processed sketch video output" || echo "No changes to commit"
          git push || echo "Push failed - check logs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This allows pushing back to the repo
