name: Create Build Release

on:
  push:
    tags:
      - 'v*build*'

permissions:
  contents: write

jobs:
  release-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup C++ environment
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
          cmake: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopencv-dev ffmpeg pkg-config

      - name: Copy CMake file
        run: |
          cp CMakeLists_build.txt CMakeLists.txt

      - name: Build release version
        run: |
          mkdir build_build
          cd build_build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Create portable package
        run: |
          mkdir -p release-package-build
          cp build_build/sketch_video_build release-package-build/
          
          cat > release-package-build/README_build.txt << 'EOF'
          Video Sketch Effect Build Application v1.0
          ==========================================
          
          USAGE: ./sketch_video_build <input_video> <output_video> [threads]
          
          EXAMPLES:
            ./sketch_video_build video.mp4 sketched_build_video.mp4
            ./sketch_video_build video.mp4 sketched_build_video.mp4 8
          
          REQUIREMENTS:
            - Ubuntu 20.04+ or similar Linux distribution
            - OpenCV 4.x (sudo apt install libopencv-dev)
            - FFmpeg (sudo apt install ffmpeg)
          EOF
          
          chmod +x release-package-build/sketch_video_build
          tar -czf video-sketch-effect-build-linux.tar.gz -C release-package-build .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Video Sketch Effect Build ${{ github.ref_name }}
          body: |
            ## Video Sketch Effect Build Release
            
            High-performance C++ build application for video sketch effects.
            
            ### Download
            - **Linux (x64) Build**: `video-sketch-effect-build-linux.tar.gz`
            
            ### Usage
            ```
            tar -xzf video-sketch-effect-build-linux.tar.gz
            cd release-package-build
            ./sketch_video_build input.mp4 output.mp4
            ```
          files: |
            video-sketch-effect-build-linux.tar.gz
            
